# Generated by Django 5.1.3 on 2024-11-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_about_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('degree_compete_year', models.CharField(max_length=200)),
            ],
        ),
    ]
