# Generated by Django 5.1.3 on 2024-12-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_my_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(upload_to='static/')),
                ('project_name', models.CharField(max_length=200)),
                ('project_detail', models.TextField()),
                ('git_link', models.TextField()),
            ],
        ),
    ]
