# Generated by Django 5.1.3 on 2024-12-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_email', models.CharField(max_length=200)),
                ('my_number', models.IntegerField()),
            ],
        ),
    ]
